/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.xl435.calculator;

import java.io.IOException;
import java.net.URL;

import edu.duke.ece651.xl435.calculator.controller.CalculatorController;
import edu.duke.ece651.xl435.calculator.controller.NumButtonController;
import edu.duke.ece651.xl435.calculator.model.RPNStack;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.RowConstraints;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import java.util.HashMap;

public class App extends Application {
    @Override
    public void start(Stage stage) throws IOException {
        // GridPane gp = new GridPane();
        // for(int i =0;i<4;i++){
        //     ColumnConstraints cc = new ColumnConstraints();
        //     cc.setPercentWidth(25);
        //     gp.getColumnConstraints().add(cc);
        // }
        // for(int i =0;i<5;i++){
        //     RowConstraints rc = new RowConstraints();
        //     rc.setPercentHeight(20);
        //     gp.getRowConstraints().add(rc);
        // }
        // String[] labels = new String[]{"+","-","*","/",
        // "7","8","9","4","5","6","1","2","3","."};
        // int rows[] = new int[]{0,0,0,0,1,1,1,2,2,2,3,3,3,4};
        // int cols[] = new int[]{0,1,2,3,0,1,2,0,1,2,0,1,2,2};
        // for(int i =0;i<labels.length;i++){
        //     Button b = new Button(labels[i]);
        //     gp.add(b,cols[i],rows[i]);
        //     b.setMaxWidth(Double.MAX_VALUE);
        //     b.setMaxHeight(Double.MAX_VALUE);
        // }
        // Button b = new Button("0");
        // b.setMaxWidth(Double.MAX_VALUE);
        // b.setMaxHeight(Double.MAX_VALUE);
        // gp.add(b,0,4,2,1);
        // b = new Button("E\nn\nt\ne\nr");
        // b.setMaxWidth(Double.MAX_VALUE);
        // b.setMaxHeight(Double.MAX_VALUE);
        // gp.add(b, 3,1,1,3);
        URL xmlResource = getClass().getResource("/ui/calc-split.xml");
        URL cssResource = getClass().getResource("/ui/calcbuttons.css");
        RPNStack model = new RPNStack();
        FXMLLoader loader = new FXMLLoader(xmlResource);


        
        HashMap<Class<?>,Object> controllers = new HashMap<>();
        controllers.put(NumButtonController.class,new NumButtonController(model));
        controllers.put(CalculatorController.class,new CalculatorController());
        loader.setControllerFactory((c)->{
            return controllers.get(c);
        });

        // GridPane gp = FXMLLoader.load(xmlResource);
        GridPane gp = loader.load();
        Scene scene = new Scene(gp, 640, 480);
        scene.getStylesheets().add(cssResource.toString());
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}

